# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('PayTm', 'PayTm'), ('PhonePe', 'PhonePe'), ('Mobikwik', 'Mobikwik'), ('Card', 'Card')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_type', models.CharField(blank=True, choices=[('R', 'Restaurants'), ('SM', 'SuperMarkets'), ('SS', 'Salon & Spa'), ('P', 'Pharmacies'), ('AS', 'Apparel Stores'), ('T', 'Taxi'), ('H', 'Hotel'), ('M', 'Movie')], max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('NA', 'NA')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='rest_api.Store'),
        ),
    ]
